"""
API Wrappers for NinjaRobot V5 — Blockly/SafeExecutor Interface.

This module provides high-level wrappers that expose a simple API
for user code generated by the Blockly visual programming IDE.

Available API:
    robot.servo[n].angle = x   - Set servo n (0-7) to angle x (0-180)
    robot.buzzer.tone(f, d)    - Play frequency f for d seconds
    robot.buzzer.play(name)    - Play emotion sound
    robot.display.clear()      - Clear display
    robot.expression(name)     - Show facial expression
    robot.distance.read()      - Read distance in mm
"""

import logging
import time
from pathlib import Path
from PIL import Image
from .robot_sound import RobotSoundPlayer
from .facial_expressions import AnimatedFaces

log = logging.getLogger(__name__)


class DistanceWrapper:
    """Wrapper for VL53L0X distance sensor."""

    def __init__(self, sensor):
        self._sensor = sensor

    def read(self):
        """Returns distance in mm from VL53L0X sensor.
        
        Returns:
            int: Distance in millimeters. Returns 9999 if sensor unavailable.
        """
        if self._sensor:
            data = self._sensor.get_data()
            return data.get("distance_mm", 9999)
        return 9999


class BuzzerWrapper:
    """Wrapper for passive buzzer with emotion sounds."""

    def __init__(self, hal):
        self._hal = hal
        self._player = RobotSoundPlayer(hal)

    def play(self, sound_name):
        """Play a predefined emotion sound by name.
        
        Valid names: happy, sad, exciting, angry, confusing, cry, 
                     embarrassing, idle, laughing, scary, shy, 
                     sleepy, speaking, surprising
        """
        self._player.play(sound_name)

    def tone(self, frequency, duration):
        """Play a specific frequency tone.
        
        Args:
            frequency: Frequency in Hz (100-2000).
            duration: Duration in seconds.
        """
        if self._hal.buzzer:
            self._hal.buzzer.execute({"frequency": frequency, "duration": duration})


class DisplayWrapper:
    """Wrapper for ST7789 display."""

    def __init__(self, hal):
        self._hal = hal
        self._search_paths = [
            Path(__file__).parent / "static" / "assets" / "images",
        ]

    def image(self, name):
        """Display an image by name (e.g., 'star' -> 'star.png')."""
        if not self._hal.display:
            return

        image_path = None
        for path in self._search_paths:
            for ext in [".png", ".jpg", ".bmp"]:
                candidate = path / f"{name}{ext}"
                if candidate.exists():
                    image_path = candidate
                    break
            if image_path:
                break

        if image_path:
            try:
                img = Image.open(image_path)
                self._hal.display.execute({"image": img})
            except Exception as e:
                log.error(f"Failed to load/display image {name}: {e}")
        else:
            log.warning(f"Image '{name}' not found in assets.")

    def clear(self):
        """Clear the display (fill with black)."""
        if self._hal.display:
            self._hal.display.execute({"clear": True})


class ServoWrapper:
    """Wrapper for a single servo motor.
    
    Blockly uses 0-180 degree range (user-friendly).
    MultiServo uses -90 to +90 degree range.
    This wrapper converts between them.
    """

    def __init__(self, multi_servo, index):
        self._multi_servo = multi_servo
        self._index = index
        self._angle = 90  # Default to center (0 in internal units)

    @property
    def angle(self):
        """Get the current angle (0-180 degrees)."""
        return self._angle

    @angle.setter
    def angle(self, value):
        """Set the servo angle (0-180 degrees).
        
        Converts from Blockly's 0-180 range to internal -90 to +90 range.
        """
        # Clamp to valid range
        value = max(0, min(180, value))
        self._angle = value
        
        # Convert 0-180 to -90 to +90
        internal_angle = value - 90
        
        if self._multi_servo and hasattr(self._multi_servo, 'servo'):
            # Use move() with default blocking duration (0.5s) to ensure sequential execution
            self.move(value, duration=0.5)
        else:
            log.warning("Servos not available")

    def move(self, angle: float, duration: float = 0.5):
        """Move this servo to angle over duration (blocking).
        
        Args:
            angle: Target angle (0-180).
            duration: Movement time in seconds (default 0.5).
        """
        # Clamp to valid range
        angle = max(0, min(180, angle))
        self._angle = angle
        
        # Convert 0-180 to -90 to +90
        internal_angle = angle - 90
        
        if self._multi_servo:
            try:
                # Construct list for MultiServo.move_all_angles_sync
                # None = don't move other servos
                # Note: We need target_angles for ALL servos, but we only want to move THIS one.
                # MultiServo.move_all_angles_sync takes a list where None means "keep current".
                
                target_angles = [None] * 8
                # We need to ensure we don't index out of bounds if self._index is weird, 
                # but it should be 0-7.
                if 0 <= self._index < 8:
                    target_angles[self._index] = internal_angle
                    self._multi_servo.move_all_angles_sync(target_angles, move_sec=duration)
                else:
                    log.error(f"Servo index {self._index} out of range")
            except Exception as e:
                log.error(f"Failed to move servo {self._index}: {e}")


class ServoArrayWrapper:
    """Wrapper that provides list-like access to servos.
    
    Allows code like: robot.servo[0].angle = 90
    """

    def __init__(self, multi_servo, count=8):
        self._multi_servo = multi_servo
        self._servos = [ServoWrapper(multi_servo, i) for i in range(count)]

    def __getitem__(self, index):
        """Get servo by index (0-7)."""
        if 0 <= index < len(self._servos):
            return self._servos[index]
        raise IndexError(f"Servo index {index} out of range (0-7)")

    def __len__(self):
        return len(self._servos)
    
    def move_all(self, angles: list, duration: float = 0.5):
        """Move all servos simultaneously.
        
        Args:
            angles (list): List of 8 angles (0-180). None to skip.
            duration (float): Time in seconds (default 0.5).
        """
        if not self._multi_servo:
            return

        internal_angles = []
        for a in angles:
            if a is not None:
                # Clamp 0-180
                val = max(0, min(180, a))
                # Convert to -90 to +90
                internal_angles.append(val - 90)
            else:
                internal_angles.append(None)
        
        try:
            self._multi_servo.move_all_angles_sync(internal_angles, move_sec=duration)
        except Exception as e:
            log.error(f"Failed to move_all: {e}")
        

    def center(self):
        """Reset all servos to center (90 degrees)."""
        self._servos.move_all_angles([90] * 8)


class RobotWrapper:
    """
    High-level wrapper for the Robot HAL.
    Matches the API expected by the Blockly/Web IDE.
    
    Available API:
        robot.servo[n].angle = x   - Set servo n (0-7) to angle x (0-180)
        robot.buzzer.tone(f, d)    - Play frequency f for d seconds
        robot.buzzer.play(name)    - Play emotion sound
        robot.display.clear()      - Clear display
        robot.expression(name)     - Show animated facial expression
        robot.distance.read()      - Read distance in mm
    """

    def __init__(self, hal):
        self._hal = hal
        self.buzzer = BuzzerWrapper(hal)
        self.display = DisplayWrapper(hal)
        self.distance = DistanceWrapper(hal.distance_sensor)
        
        # Servos: wrap MultiServo to provide list-like access
        # robot.servo[n].angle = x
        self.servo = ServoArrayWrapper(hal.servos)
        self.servos = self.servo  # Alias for plural access (semantic sugar)
        
        # Facial expressions engine
        self._faces = AnimatedFaces(hal)

    def expression(self, name: str, duration: float = 2.0):
        """Show an animated facial expression on the display.
        
        Args:
            name: Expression name. Valid options:
                  happy, sad, sleepy, surprising, angry, shy, confusing,
                  scary, exciting, cry, laughing, speaking, idle,
                  embarrassing
            duration: How long to show the expression (default 2 seconds).
        """
        if self._faces:
            try:
                # AnimatedFaces uses play() method
                self._faces.play(name, duration_s=duration)
                # Block for duration to ensure animation completes before next command
                time.sleep(duration)
            except Exception as e:
                log.error(f"Failed to show expression '{name}': {e}")
        else:
            log.warning("AnimatedFaces not available.")
