"""
API Wrappers for NinjaRobot V5 — Blockly/SafeExecutor Interface.

This module provides high-level wrappers that expose a simple API
for user code generated by the Blockly visual programming IDE.

Available API (V5.2.1 - ±90° standardized):
    robot.servo[n].angle = x   - Set servo n (0-7) to angle x (±90°)
    robot.buzzer.tone(f, d)    - Play frequency f for d seconds
    robot.buzzer.play(name)    - Play emotion sound
    robot.display.clear()      - Clear display
    robot.expression(name)     - Show facial expression
    robot.distance.read()      - Read distance in mm
"""

import logging
import time
from pathlib import Path
from PIL import Image
from .robot_sound import RobotSoundPlayer
from .facial_expressions import AnimatedFaces

log = logging.getLogger(__name__)


class DistanceWrapper:
    """Wrapper for VL53L0X distance sensor."""

    def __init__(self, sensor):
        self._sensor = sensor

    def read(self):
        """Returns distance in mm from VL53L0X sensor.
        
        Returns:
            int: Distance in millimeters. Returns 9999 if sensor unavailable.
        """
        if self._sensor:
            data = self._sensor.get_data()
            return data.get("distance_mm", 9999)
        return 9999


class BuzzerWrapper:
    """Wrapper for passive buzzer with emotion sounds."""

    def __init__(self, hal):
        self._hal = hal
        self._player = RobotSoundPlayer(hal)

    def play(self, sound_name):
        """Play a predefined emotion sound by name.
        
        Valid names: happy, sad, exciting, angry, confusing, cry, 
                     embarrassing, idle, laughing, scary, shy, 
                     sleepy, speaking, surprising
        """
        self._player.play(sound_name)

    def tone(self, frequency, duration):
        """Play a specific frequency tone.
        
        Args:
            frequency: Frequency in Hz (100-2000).
            duration: Duration in seconds.
        """
        if self._hal.buzzer:
            self._hal.buzzer.execute({"frequency": frequency, "duration": duration})


class DisplayWrapper:
    """Wrapper for ST7789 display."""

    def __init__(self, hal):
        self._hal = hal
        self._search_paths = [
            Path(__file__).parent / "static" / "assets" / "images",
        ]

    def image(self, name):
        """Display an image by name (e.g., 'star' -> 'star.png')."""
        if not self._hal.display:
            return

        image_path = None
        for path in self._search_paths:
            for ext in [".png", ".jpg", ".bmp"]:
                candidate = path / f"{name}{ext}"
                if candidate.exists():
                    image_path = candidate
                    break
            if image_path:
                break

        if image_path:
            try:
                img = Image.open(image_path)
                self._hal.display.execute({"image": img})
            except Exception as e:
                log.error(f"Failed to load/display image {name}: {e}")
        else:
            log.warning(f"Image '{name}' not found in assets.")

    def clear(self):
        """Clear the display (fill with black)."""
        if self._hal.display:
            self._hal.display.execute({"clear": True})


class ServoWrapper:
    """Wrapper for a single servo motor.

    Uses ±90° angle range directly (V5.2.1 standardization).
    Center position is 0°, full range is -90° to +90°.
    """

    def __init__(self, multi_servo, index):
        self._multi_servo = multi_servo
        self._index = index
        self._angle = 0  # Default to center (0°)

    @property
    def angle(self):
        """Get the current angle (±90°)."""
        return self._angle

    @angle.setter
    def angle(self, value):
        """Set the servo angle (±90°).

        No conversion needed - uses ±90° range directly.
        """
        # Clamp to valid ±90° range
        value = max(-90, min(90, value))
        self._angle = value

        if self._multi_servo and hasattr(self._multi_servo, 'servo'):
            # Use move() with default blocking duration (0.5s)
            self.move(value, duration=0.5)
        else:
            log.warning("Servos not available")

    def move(self, angle: float, duration: float = 0.5):
        """Move this servo to angle over duration (blocking).

        Args:
            angle: Target angle (±90°).
            duration: Movement time in seconds (default 0.5).
        """
        # Clamp to valid ±90° range
        angle = max(-90, min(90, angle))
        self._angle = angle

        if self._multi_servo:
            try:
                # Construct list for ServoGroup.move_all_angles_sync
                # None = don't move other servos
                target_angles = [None] * 8
                if 0 <= self._index < 8:
                    target_angles[self._index] = angle  # No conversion needed
                    self._multi_servo.move_all_angles_sync(target_angles, move_sec=duration)
                else:
                    log.error(f"Servo index {self._index} out of range")
            except Exception as e:
                log.error(f"Failed to move servo {self._index}: {e}")


class ServoArrayWrapper:
    """Wrapper that provides list-like access to servos.

    Allows code like: robot.servo[0].angle = 45  (±90° range)
    """

    def __init__(self, multi_servo, count=8):
        self._multi_servo = multi_servo
        self._servos = [ServoWrapper(multi_servo, i) for i in range(count)]

    def __getitem__(self, index):
        """Get servo by index (0-7)."""
        if 0 <= index < len(self._servos):
            return self._servos[index]
        raise IndexError(f"Servo index {index} out of range (0-7)")

    def __len__(self):
        return len(self._servos)

    @property
    def pins(self) -> list[int]:
        """Get list of GPIO pins from underlying ServoGroup."""
        if self._multi_servo:
            return self._multi_servo.pins
        return []

    def get_all_angles(self) -> list[float]:
        """Get current angles from all servos."""
        if self._multi_servo:
            return self._multi_servo.get_all_angles()
        return [0.0] * len(self._servos)

    def move_all_sync(
        self,
        targets: list[float | None],
        speed_mode: str | list[str] = "M",
        easing: str = "ease_out",
    ) -> bool:
        """Move all servos with per-servo speed control.

        Wrapper for ServoGroup.move_all_sync.

        Args:
            targets: List of target angles. None = don't move.
            speed_mode: Single mode or list of modes per servo.
            easing: Easing function name.

        Returns:
            True if completed, False if aborted.
        """
        if not self._multi_servo:
            return True

        try:
            return self._multi_servo.move_all_sync(
                targets, speed_mode=speed_mode, easing=easing
            )
        except Exception as e:
            log.error(f"Failed to move_all_sync: {e}")
            return False

    def move_all_angles(self, targets: list[float | None]):
        """Instant movement (no interpolation).

        Args:
            targets: List of target angles. None = don't move.
        """
        if self._multi_servo:
            try:
                self._multi_servo.move_all_angles(targets)
            except Exception as e:
                log.error(f"Failed to move_all_angles: {e}")

    def move_all(self, angles: list, duration: float = 0.5):
        """Move all servos simultaneously (legacy API).

        Args:
            angles (list): List of 8 angles (±90°). None to skip.
            duration (float): Time in seconds (default 0.5).
        """
        if not self._multi_servo:
            return

        # No conversion needed - pass angles directly
        clamped_angles = []
        for a in angles:
            if a is not None:
                clamped_angles.append(max(-90, min(90, a)))
            else:
                clamped_angles.append(None)

        try:
            self._multi_servo.move_all_angles_sync(clamped_angles, move_sec=duration)
        except Exception as e:
            log.error(f"Failed to move_all: {e}")

    def center(self):
        """Reset all servos to center (0°)."""
        self.move_all([0] * 8)


class RobotWrapper:
    """
    High-level wrapper for the Robot HAL.
    Matches the API expected by the Blockly/Web IDE.

    Available API (V5.2.1 - ±90° standardized):
        robot.servo[n].angle = x   - Set servo n (0-7) to angle x (±90°)
        robot.buzzer.tone(f, d)    - Play frequency f for d seconds
        robot.buzzer.play(name)    - Play emotion sound
        robot.display.clear()      - Clear display
        robot.expression(name)     - Show animated facial expression
        robot.distance.read()      - Read distance in mm
    """

    def __init__(self, hal):
        self._hal = hal
        self.buzzer = BuzzerWrapper(hal)
        self.display = DisplayWrapper(hal)
        self.distance = DistanceWrapper(hal.distance_sensor)
        
        # Servos: wrap MultiServo to provide list-like access
        # robot.servo[n].angle = x
        self.servo = ServoArrayWrapper(hal.servos)
        self.servos = self.servo  # Alias for plural access (semantic sugar)
        
        # Facial expressions engine
        self._faces = AnimatedFaces(hal)

    def expression(self, name: str, duration: float = 2.0):
        """Show an animated facial expression on the display.
        
        Args:
            name: Expression name. Valid options:
                  happy, sad, sleepy, surprising, angry, shy, confusing,
                  scary, exciting, cry, laughing, speaking, idle,
                  embarrassing
            duration: How long to show the expression (default 2 seconds).
        """
        if self._faces:
            try:
                # AnimatedFaces uses play() method
                self._faces.play(name, duration_s=duration)
                # Block for duration to ensure animation completes before next command
                time.sleep(duration)
            except Exception as e:
                log.error(f"Failed to show expression '{name}': {e}")
        else:
            log.warning("AnimatedFaces not available.")
