/**
 * @file BlocklyWorkspace.jsx
 * @description Blockly workspace component with NinjaRobot custom blocks.
 */

import { useRef, useEffect } from 'react';
import * as Blockly from 'blockly';
import 'blockly/python';
import { toolbox } from '../../services/blockly/toolbox';
import styles from './BlocklyWorkspace.module.css';

// Import blocks (side-effect registration)
import '../../services/blockly/blocks';

function BlocklyWorkspace({ onCodeChange, workspaceRef: externalRef }) {
    const containerRef = useRef(null);
    const workspaceRef = useRef(null);
    const onCodeChangeRef = useRef(onCodeChange);

    // Update ref when callback changes
    useEffect(() => {
        onCodeChangeRef.current = onCodeChange;
    }, [onCodeChange]);

    useEffect(() => {
        if (!containerRef.current || workspaceRef.current) return;

        // Inject Blockly workspace
        const workspace = Blockly.inject(containerRef.current, {
            toolbox,
            theme: Blockly.Themes.Classic,
            grid: {
                spacing: 20,
                length: 3,
                colour: '#ccc',
                snap: true,
            },
            zoom: {
                controls: true,
                wheel: true,
                startScale: 1.0,
                maxScale: 3,
                minScale: 0.3,
                scaleSpeed: 1.2,
            },
            trashcan: true,
            move: {
                scrollbars: true,
                drag: true,
                wheel: true,
            },
        });

        workspaceRef.current = workspace;

        if (externalRef) {
            externalRef.current = workspace;
        }

        // Code generation
        const generateCode = () => {
            requestAnimationFrame(() => {
                import('../../services/blockly/generators').then(({ pythonGenerator }) => {
                    const header = `# NinjaRobot Code - Generated by NinjaRobot Web IDE
import time
from ninja_core import robot

`;
                    try {
                        const code = pythonGenerator.workspaceToCode(workspace);
                        if (onCodeChangeRef.current) {
                            onCodeChangeRef.current(header + code);
                        }
                    } catch (e) {
                        console.error('Code generation error:', e);
                    }
                });
            });
        };

        // Debounced change handler
        let debounceTimer = null;
        const handleChange = (event) => {
            if (event.isUiEvent) return;

            if (
                event.type === Blockly.Events.BLOCK_CHANGE ||
                event.type === Blockly.Events.BLOCK_CREATE ||
                event.type === Blockly.Events.BLOCK_DELETE ||
                event.type === Blockly.Events.BLOCK_MOVE
            ) {
                if (debounceTimer) clearTimeout(debounceTimer);
                debounceTimer = setTimeout(generateCode, 200);
            }
        };

        workspace.addChangeListener(handleChange);

        // Resize handler
        const handleResize = () => Blockly.svgResize(workspace);
        window.addEventListener('resize', handleResize);
        setTimeout(() => Blockly.svgResize(workspace), 100);

        return () => {
            if (debounceTimer) clearTimeout(debounceTimer);
            window.removeEventListener('resize', handleResize);
            workspace.dispose();
            workspaceRef.current = null;
        };
    }, [externalRef]);

    return (
        <div className={styles.workspace}>
            <div ref={containerRef} className={styles.blocklyContainer} />
        </div>
    );
}

export default BlocklyWorkspace;
