import { useRef, useCallback, useState } from 'react';
import * as Blockly from 'blockly';
import { pythonGenerator } from '../services/blockly';

/**
 * Custom hook for managing Blockly workspace state
 */
const useBlockly = () => {
    const workspaceRef = useRef(null);
    const [code, setCode] = useState('# Your code will appear here\n');

    /**
     * Generate Python code from workspace
     */
    const generateCode = useCallback((workspace) => {
        const ws = workspace || workspaceRef.current;
        if (!ws) return '';

        try {
            // Add imports header
            const header = `# NinjaRobot Code - Generated by NinjaRobot Code IDE
# Compatible with NinjaRobot V5 HAL

import time
from ninja_core import robot

`;
            const generatedCode = pythonGenerator.workspaceToCode(ws);
            const fullCode = header + generatedCode;
            setCode(fullCode);
            return fullCode;
        } catch (error) {
            console.error('Code generation error:', error);
            setCode('# Error generating code');
            return '';
        }
    }, []);

    /**
     * Inject Blockly workspace into a container element
     */
    const injectWorkspace = useCallback((container, toolbox) => {
        if (workspaceRef.current) {
            workspaceRef.current.dispose();
        }

        const workspace = Blockly.inject(container, {
            toolbox,
            theme: Blockly.Themes.Classic,
            grid: {
                spacing: 20,
                length: 3,
                colour: '#ccc',
                snap: true,
            },
            zoom: {
                controls: true,
                wheel: true,
                startScale: 1.0,
                maxScale: 3,
                minScale: 0.3,
                scaleSpeed: 1.2,
            },
            trashcan: true,
            move: {
                scrollbars: true,
                drag: true,
                wheel: true,
            },
        });

        // Listen for workspace changes
        workspace.addChangeListener((event) => {
            if (
                event.type === Blockly.Events.BLOCK_CHANGE ||
                event.type === Blockly.Events.BLOCK_CREATE ||
                event.type === Blockly.Events.BLOCK_DELETE ||
                event.type === Blockly.Events.BLOCK_MOVE
            ) {
                generateCode(workspace);
            }
        });

        workspaceRef.current = workspace;
        return workspace;
    }, [generateCode]);

    /**
     * Get workspace reference (for use in effects/handlers only)
     */
    const getWorkspace = useCallback(() => {
        return workspaceRef.current;
    }, []);

    /**
     * Clear the workspace
     */
    const clearWorkspace = useCallback(() => {
        if (workspaceRef.current) {
            workspaceRef.current.clear();
            setCode('# Your code will appear here\n');
        }
    }, []);

    /**
     * Get workspace XML for saving
     */
    const getWorkspaceXml = useCallback(() => {
        if (!workspaceRef.current) return '';
        const xml = Blockly.Xml.workspaceToDom(workspaceRef.current);
        return Blockly.Xml.domToText(xml);
    }, []);

    /**
     * Load workspace from XML
     */
    const loadWorkspaceXml = useCallback((xmlText) => {
        if (!workspaceRef.current || !xmlText) return;
        try {
            workspaceRef.current.clear();
            const xml = Blockly.utils.xml.textToDom(xmlText);
            Blockly.Xml.domToWorkspace(xml, workspaceRef.current);
        } catch (error) {
            console.error('Error loading workspace:', error);
        }
    }, []);

    /**
     * Dispose of workspace
     */
    const dispose = useCallback(() => {
        if (workspaceRef.current) {
            workspaceRef.current.dispose();
            workspaceRef.current = null;
        }
    }, []);

    return {
        code,
        getWorkspace,
        injectWorkspace,
        generateCode,
        clearWorkspace,
        getWorkspaceXml,
        loadWorkspaceXml,
        dispose,
    };
};

export default useBlockly;
